groups:
- name: example
  rules:

  - alert: HighHostOutOfMemore9
    expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
    # for: 1m
    labels:
      severity: high
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HighCPUe9
    expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
    # for: 1m
    labels:
      severity: medium
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: Highfragmentationratio7
    expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
    # for: 1m
    labels:
      severity: warning
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  # - alert: Memoryabove90%e
  #   expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
  #     # for: 1m
  #   labels:
  #       severity: high
  #   annotations:
  #       summary: Host out of memory (instance {{ $labels.instance }})
  #       description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  # - alert: MemoryAPIerrore
  #   expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
  #   # for: 1m
  #   labels:
  #     severity: medium
  #   annotations:
  #     summary: Host out of memory (instance {{ $labels.instance }})
  #     description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  # - alert: alert5e
  #   expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 5
  #   # for: 1m
  #   labels:
  #     severity: low
  #   annotations:
  #     summary: Host out of memory (instance {{ $labels.instance }})
  #     description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"